apiVersion: v1
kind: Service
metadata:
  name: bookinfo-details
  labels:
    app: bookinfo-details
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: bookinfo-details
  type: ClusterIP